#!/bin/env fish

for tool in (asdf plugin-list)
  set current_version (asdf current $tool 2>/dev/null | string split --no-empty --fields 2 -- ' ')
  for tool_version in (asdf list $tool | string trim)
    if test "$tool_version" != "$current_version"
      echo "Removing version '$tool_version' of $tool"
      asdf uninstall "$tool" "$tool_version"
    end
  end
end
