#!/bin/sh

# Exit if a command returns a non-zero exit code
set -o errexit

# Exit if an unset variable is referenced
set -o nounset

# save the current terminal title
printf "\033[22;0t"

if chronic pkill --signal SIGUSR1 --full "(^x\-terminal\-emulator|^kitty|^$(realpath "$(which kitty)"))"; then
  new_title="${1}terminal reload successful"
else
  new_title="${1}terminal reload failed"
fi
printf "\033]0;%s\007" "$new_title"

# In five seconds, set the terminal title back to what it what it was before I changed it
( (sleep 5; printf "\033[23;0t") & )
