#!/bin/bash

mode=''

case $1 in

  "day")
    # for unused in {1..5}; do
    #   set_brightness up
    # done
    mode='day'
    ;;

  "night")
    # for unused in {1..5}; do
    #   set_brightness down
    # done
    mode='night'
    ;;

  *)
    if realpath ~/.config/kitty/current-theme.conf | grep -q 'day'; then
      mode='night'
    else
      mode='day'
    fi
    ;;
esac

# Change kitty theme
ln -sf ~/.config/kitty/"$mode"-theme.conf ~/.config/kitty/current-theme.conf
command -v reload-kitty >/dev/null 2>&1 && reload-kitty
