#!/bin/bash

mode=''

case $1 in

  "day")
    # for unused in {1..5}; do
    #   set_brightness up
    # done
    mode='day'
    ;;

  "night")
    # for unused in {1..5}; do
    #   set_brightness down
    # done
    mode='night'
    ;;

  *)
    echo 'invalid argument, use "day" or "night"'
    exit 1
    ;;
esac

# Change kitty theme
ln -sf ~/.config/kitty/"$mode"-theme.conf ~/.config/kitty/current-theme.conf
killall --signal SIGUSR1 kitty x-terminal-emulator
