#!/bin/bash

# Copy the source folder, excluding the .venv since the virtual environment will be recreated in the target directory
sudo rsync -arhP --exclude='.venv' smart-plug-daemon.d /opt/
cd /opt/smart-plug-daemon.d
# Creating this folder so that pipenv stores the virtual environment in it
mkdir .venv
pipenv install
cd -

sudo cp smart-plug-daemon.service /etc/systemd/system/
sudo systemctl enable smart-plug-daemon.service
sudo systemctl start smart-plug-daemon.service
