# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json

# By default lefthook uses true colors (e.g. #FFFFFF), but they may not be
# readable depending on the terminal background color. Instead I'm using ANSI
# colors since they come from the terminal's color palette.
colors:
  cyan: 6
  gray: 8
  green: 2
  red: 1
  yellow: 3

output: false

pre-commit:
  piped: true
  commands:
    # Code generators
    generate-readme-table-of-contents:
      priority: 1
      glob: "README.md"
      run: DIRENV_LOG_FORMAT='' direnv exec "$PWD" just generate-readme-table-of-contents
    generate-neovim-plugin-list:
      priority: 1
      glob: "*neovim/lua/*.lua"
      run: DIRENV_LOG_FORMAT='' direnv exec "$PWD" just generate-neovim-plugin-list
    go-mod-tidy:
      priority: 1
      glob: "*gozip/go.mod"
      run: DIRENV_LOG_FORMAT='' direnv exec "$PWD" just go-mod-tidy
    gomod2nix:
      priority: 1
      glob: "*gozip/go.mod"
      run: DIRENV_LOG_FORMAT='' direnv exec "$PWD" just gomod2nix

    # Formatters. Change their priority so we format code after all the code
    # generators have run
    format:
      priority: 2
      run: DIRENV_LOG_FORMAT='' direnv exec "$PWD" just format {staged_files}
      interactive: true
    format-all:
      priority: 2
      glob: "{.stylua.toml,.editorconfig,treefmt.toml}"
      run: DIRENV_LOG_FORMAT='' direnv exec "$PWD" just format
      interactive: true

    # Linters. Change the priority so we lint the code after all code generation
    # and formatting has run, in the unlikely event that they cause a lint
    # error.
    lint:
      priority: 3
      run: DIRENV_LOG_FORMAT='' direnv exec "$PWD" just lint {staged_files}

post-merge:
  scripts:
    "post-merge.bash":
      runner: DIRENV_LOG_FORMAT='' direnv exec "$PWD" bash
      interactive: true

post-rewrite:
  scripts:
    "post-rewrite.bash":
      runner: DIRENV_LOG_FORMAT='' direnv exec "$PWD" bash
      interactive: true
