#!/bin/sh

# Exit if a command returns a non-zero exit code
set -o errexit

# Exit if an unset variable is referenced
set -o nounset

tempfile="$(mktemp --suffix '.txt')"
xclip -selection clipboard -out > "$tempfile"
$EDITOR "$tempfile"
