#!/bin/sh

# Exit if a command returns a non-zero exit code
set -o errexit

# Exit if an unset variable is referenced
set -o nounset

echo "Would you like to setup fbterm? (y/n): "
read -r response
if [ "$response" != "y" ]; then
  exit
fi

sudo setcap 'cap_sys_tty_config+ep' "$(command -v fbterm)"
sudo usermod -aG video "$USER"
