#!/usr/bin/env sh

# If Firefox Developer Edition is open, use that instead of normal firefox.

# Exit if a command returns a non-zero exit code
set -o errexit

# Exit if an unset variable is referenced
set -o nounset

if ! command -v firefox-developer-edition >/dev/null 2>&1; then
  firefox "$@"
  exit
fi

# The .desktop entry executes the binary in /opt so I have to look for that.
if pgrep --full '/opt/firefox' >/dev/null 2>&1; then
  firefox-developer-edition "$@"
else
  firefox "$@"
fi
