#!/usr/bin/env sh

# Exit if a command returns a non-zero exit code
set -o errexit

# Exit if an unset variable is referenced
set -o nounset

if [ $# -eq 0 ]; then
    echo "ERROR: You must provide the number of commits to rebase"
    exit 1
fi

git rebase -i "HEAD~$1"
