#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_DIR="$(cd "$BASEDIR" && git rev-parse --show-toplevel)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# The shell commands that I run with Dotbot are in POSIX shell so I need to set my $SHELL to it.
SHELL="$(command -v sh)" "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${REPO_ROOT_DIR}" -c "${CONFIG}" "${@}"
