name: Publish Shell Executable
on:
  push:
    paths:
      - ".github/workflows/publish-shell-executable.yml"
      - "flake.nix"
      - "flake.lock"
      - "flake-modules/**"
      - "dotfiles/**"
    branches:
      - master
env:
  # The checkout action clones the repository relative to github.workspace. I
  # set $HOME to github.workspace so that the directory structure matches that
  # of the machine I tested this on.
  HOME: ${{ github.workspace }}
jobs:
  publish-executable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest uses M1 so I'll just use the most recent version of macOS
        # that they still on run intel macs
        os: [ubuntu-latest, macos-13]
      fail-fast: false
    defaults:
      run:
        working-directory: "code/system-configurations"
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          path: "code/system-configurations"
      - uses: DeterminateSystems/nix-installer-action@main
        # TODO: bundle fails with latest so I'm pinning the same version I
        # pinned in the cache workflow
        # https://github.com/nix-community/home-manager/issues/4692
        # https://github.com/NixOS/nix/issues/9579
        with:
          source-tag: v0.13.1
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: bigolu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          # TODO: This isn't working right now:
          # https://github.com/cachix/cachix-action/issues/169
          useDaemon: false
      - run: nix run --show-trace .#nix -- bundle --show-trace --bundler .# .#shellMinimal
      - run: NIXPKGS_ALLOW_UNFREE=1 nix run --show-trace .#nix -- bundle --impure --show-trace --bundler .# .#terminalMinimal
      # Dereference the symlinks so I can upload the actual executables. The symlinks' names will
      # look like '<name>-x86_64-linux' so I'm using a glob pattern to match
      # them.
      - run: |
          mkdir tmp
          cp -L shell-* ./tmp/
          cp -L terminal-* ./tmp/
      - run: |
          size="$(du -m ./tmp/shell-* | cut -f1)"
          max_size='250'
          if (( "$size" > "$max_size" )); then
          echo "Shell is too big: $size MB. Max size: $max_size"
            exit 1
          fi
      - name: Upload executable
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
        with:
          file: "${{ env.HOME }}/code/system-configurations/tmp/*"
          file_glob: true
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.0.1
