name: "Renovate Post-Upgrade Task"
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    secrets:
      BIGOLU_BOT_PRIVATE_KEY:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
env:
  # The checkout action clones the repository relative to github.workspace. I
  # set $HOME to github.workspace so that the directory structure matches that
  # of the machine I tested this on.
  HOME: ${{ github.workspace }}
jobs:
  renovate-post-upgrade-task:
    runs-on: ubuntu-latest
    # TODO: This will result in a bunch of runs that immediately exit if the branch wasn't just created. Ideally the job wouldn't even start if the branch wasn't just created:
    # https://github.com/orgs/community/discussions/39831
    # https://github.com/orgs/community/discussions/54860
    # https://github.com/orgs/community/discussions/26286
    #
    # SYNC: RENOVATE_FIXUP
    if: startsWith(github.event.head_commit.message, '[RENOVATE_FIXUP]')
    defaults:
      run:
        working-directory: "code/system-configurations"
    steps:
      - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: bigolu-bot-app-token
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          path: "code/system-configurations"
          # So when we commit, it triggers other workflows:
          # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ steps.bigolu-bot-app-token.outputs.token }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: bigolu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          # TODO: This isn't working right now:
          # https://github.com/cachix/cachix-action/issues/169
          useDaemon: false
      - run: ${{ inputs.command }}
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          repository: "code/system-configurations"
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@48b6133aa6c826f267ebd33aa2d29470f9d9e7d0 # v1
        id: find-pull-request
        with:
          branch: ${{ github.ref_name }}
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ steps.bigolu-bot-app-token.outputs.token }}
          pr-number: ${{ steps.find-pull-request.outputs.number }}
          configuration-path: code/system-configurations/.github/labeler.yml
